package org.firstinspires.ftc.teamcode.GMR.Autonomous;

/**
 * Created by pston on 12/31/2017
 */

public enum State {

    END,
    ROTATE,
    DRIVEOUT,
    DRIVECRATER,
    DRIVEMARKER,
    DROPSOAS,
    RAISEHOOK,
    TURNRIGHT,
    RAISESERVO,
    ROTATEBOT,
    DRIVEFORWARD,
    LOWERARM,
    ROTATECRATER,
    DRIVEMID,
    TURNLEFT,
    ROTATERIGHT,
    ROTATELEFT,
    SAMPLING,
    KNOCKLEFT,
    KNOCKCENTER,
    KNOCKRIGHT,
    RETURNLEFT,
    RETURNCENTER,
    RETURNRIGHT,
    STRAFE,
    LEFTFORWARD,
    RIGHTFORWARD,
    LEFTBACKWARDS,
    RIGHTBACKWARDS,
    LEFTROTATION,
    RIGHTROTATION,
    DELAY,
    STRAFELEFT,
    DRIVEBACKWARD,
    DRIVERIGHT,
    DRIVELEFT,
    DRIVETODEPOT,
    DRIVETWALL,
    DRIVEDEPOT,
    DRIVETOWALL

}
